<a href="https://colab.research.google.com/github/georgeduranh/ML/blob/main/0_pandas/5_handling_null_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dict = {'col1': [0,1,2,3, np.nan],
 'col2': [0,np.nan,2,3, np.nan],
 'col3': ['A','B', 'C', 'D', None]}

In [5]:
df = pd.DataFrame(dict)

In [6]:
df

   col1  col2  col3
0   0.0   0.0     A
1   1.0   NaN     B
2   2.0   2.0     C
3   3.0   3.0     D
4   NaN   NaN  None

In [7]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False  False
4   True   True   True

In [8]:
df.isnull()*1

   col1  col2  col3
0     0     0     0
1     0     1     0
2     0     0     0
3     0     0     0
4     1     1     1

In [9]:
df.fillna('Missing')

      col1     col2     col3
0      0.0      0.0        A
1      1.0  Missing        B
2      2.0      2.0        C
3      3.0      3.0        D
4  Missing  Missing  Missing

In [10]:
df.fillna(df.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

   col1      col2  col3
0   0.0  0.000000     A
1   1.0  1.666667     B
2   2.0  2.000000     C
3   3.0  3.000000     D
4   1.5  1.666667  None

In [11]:
df.interpolate()

   col1  col2  col3
0   0.0   0.0     A
1   1.0   1.0     B
2   2.0   2.0     C
3   3.0   3.0     D
4   3.0   3.0  None

In [12]:
df.dropna()

   col1  col2 col3
0   0.0   0.0    A
2   2.0   2.0    C
3   3.0   3.0    D